// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsjjjdwpwkesuytrjykl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzampqZHdwd2tlc3V5dHJqeWtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYxODQ3NjYsImV4cCI6MjEwMTc2MDc2Nn0.S07l2gtBWEhHv7nwTEZK-Xj-qdY2r5izhMpJ4bF8KuM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});